### ISSUE TITLE
crash on exit with 3rd party audio units

### ISSUE THREAD

**Issue by jefftimesten** [admsyn/ofxAudioUnit#22]
Granite: http://www.newsonicarts.com/html/granite.php
The Mangle: http://sound-guru.com/software/mangle/

Both cause crash on exit at https://github.com/admsyn/ofxAudioUnit/blob/master/src/ofxAudioUnit.cpp#L83

Hardly the worst thing in the world, but gets a little annoying. I'm digging in now.

**Comment by admsyn** [comment]
Hey @jefftimesten, I've run into this a few times (with Native Instruments' stuff specifically). I'm *pretty* sure it's due to the way exit signal handling is managed in OF, or something equally out of reach of this addon. My reasoning is that once that "dispose" line is hit, the units have already responded to the exit signal (or something) and are in a weird state, such that the "dispose" function errors out.

 I'll keep an eye out for it in general, but I don't think this is an issue that can be solved from within ofxAudioUnit.

If there's a workaround you've come up with I'd be glad to hear it though!
